// Mock de lucide-react-native — todos los iconos como null
const Icon = () => null;

export const Car           = Icon;
export const MapPin        = Icon;
export const CheckCircle   = Icon;
export const Clock         = Icon;
export const LogOut        = Icon;
export const Navigation    = Icon;
export const AlertTriangle = Icon;
export const ArrowLeft     = Icon;
export const Star          = Icon;
export const Settings      = Icon;
export const User          = Icon;
export const ChevronRight  = Icon;
export const ChevronLeft   = Icon;
export const X             = Icon;
export const Check         = Icon;
export const Info          = Icon;
export const AlertCircle   = Icon;
export const Loader        = Icon;
export const Eye           = Icon;
export const EyeOff        = Icon;
export const Lock          = Icon;
export const Mail          = Icon;
export const Bell          = Icon;
export const History       = Icon;
export const Flag          = Icon;
export const BookOpen      = Icon;
export const HelpCircle    = Icon;
export const Timer         = Icon;
export const XCircle       = Icon;
